# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20171003_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitant',
            name='system_user',
            field=models.BooleanField(default=False),
        ),
    ]
